# Generated by Django 3.1.6 on 2021-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
                ('status', models.CharField(default='notompleted', max_length=15)),
                ('user', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
