# Generated by Django 3.1.6 on 2021-05-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
